package cn.lgw.learn.mapper;

import cn.lgw.learn.domain.borrowRecordDO;
import cn.lgw.learn.domain.condition.borrowRecordCondition;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface borrowRecordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_record
     *
     * @mbggenerated Sat Mar 17 23:19:27 CST 2018
     */
    int countByExample(borrowRecordCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_record
     *
     * @mbggenerated Sat Mar 17 23:19:27 CST 2018
     */
    int deleteByExample(borrowRecordCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_record
     *
     * @mbggenerated Sat Mar 17 23:19:27 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_record
     *
     * @mbggenerated Sat Mar 17 23:19:27 CST 2018
     */
    int insert(borrowRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_record
     *
     * @mbggenerated Sat Mar 17 23:19:27 CST 2018
     */
    int insertSelective(borrowRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_record
     *
     * @mbggenerated Sat Mar 17 23:19:27 CST 2018
     */
    List<borrowRecordDO> selectByExample(borrowRecordCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_record
     *
     * @mbggenerated Sat Mar 17 23:19:27 CST 2018
     */
    borrowRecordDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_record
     *
     * @mbggenerated Sat Mar 17 23:19:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") borrowRecordDO record, @Param("example") borrowRecordCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_record
     *
     * @mbggenerated Sat Mar 17 23:19:27 CST 2018
     */
    int updateByExample(@Param("record") borrowRecordDO record, @Param("example") borrowRecordCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_record
     *
     * @mbggenerated Sat Mar 17 23:19:27 CST 2018
     */
    int updateByPrimaryKeySelective(borrowRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_record
     *
     * @mbggenerated Sat Mar 17 23:19:27 CST 2018
     */
    int updateByPrimaryKey(borrowRecordDO record);
}