package cn.lgw.learn.mapper;

import cn.lgw.learn.domain.condition.repositoryCondition;
import cn.lgw.learn.domain.repositoryDO;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface repositoryDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbggenerated Sat Mar 17 23:19:27 CST 2018
     */
    int countByExample(repositoryCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbggenerated Sat Mar 17 23:19:27 CST 2018
     */
    int deleteByExample(repositoryCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbggenerated Sat Mar 17 23:19:27 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbggenerated Sat Mar 17 23:19:27 CST 2018
     */
    int insert(repositoryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbggenerated Sat Mar 17 23:19:27 CST 2018
     */
    int insertSelective(repositoryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbggenerated Sat Mar 17 23:19:27 CST 2018
     */
    List<repositoryDO> selectByExample(repositoryCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbggenerated Sat Mar 17 23:19:27 CST 2018
     */
    repositoryDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbggenerated Sat Mar 17 23:19:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") repositoryDO record, @Param("example") repositoryCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbggenerated Sat Mar 17 23:19:27 CST 2018
     */
    int updateByExample(@Param("record") repositoryDO record, @Param("example") repositoryCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbggenerated Sat Mar 17 23:19:27 CST 2018
     */
    int updateByPrimaryKeySelective(repositoryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbggenerated Sat Mar 17 23:19:27 CST 2018
     */
    int updateByPrimaryKey(repositoryDO record);
}