package cn.lgw.learn.mapper;

import cn.lgw.learn.domain.condition.userCondition;
import cn.lgw.learn.domain.userDO;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface userDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Mar 17 23:19:27 CST 2018
     */
    int countByExample(userCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Mar 17 23:19:27 CST 2018
     */
    int deleteByExample(userCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Mar 17 23:19:27 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Mar 17 23:19:27 CST 2018
     */
    int insert(userDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Mar 17 23:19:27 CST 2018
     */
    int insertSelective(userDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Mar 17 23:19:27 CST 2018
     */
    List<userDO> selectByExample(userCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Mar 17 23:19:27 CST 2018
     */
    userDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Mar 17 23:19:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") userDO record, @Param("example") userCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Mar 17 23:19:27 CST 2018
     */
    int updateByExample(@Param("record") userDO record, @Param("example") userCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Mar 17 23:19:27 CST 2018
     */
    int updateByPrimaryKeySelective(userDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Mar 17 23:19:27 CST 2018
     */
    int updateByPrimaryKey(userDO record);
}