package cn.xf.learn.domin.condition;

import java.util.ArrayList;
import java.util.List;

public class PersonCondition {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table person
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table person
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    protected String limit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table person
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table person
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    public PersonCondition() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    public void setLimit(String limit) {
        this.limit = limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    public String getLimit() {
        return limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table person
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andStuNameIsNull() {
            addCriterion("stu_name is null");
            return (Criteria) this;
        }

        public Criteria andStuNameIsNotNull() {
            addCriterion("stu_name is not null");
            return (Criteria) this;
        }

        public Criteria andStuNameEqualTo(String value) {
            addCriterion("stu_name =", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameNotEqualTo(String value) {
            addCriterion("stu_name <>", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameGreaterThan(String value) {
            addCriterion("stu_name >", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameGreaterThanOrEqualTo(String value) {
            addCriterion("stu_name >=", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameLessThan(String value) {
            addCriterion("stu_name <", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameLessThanOrEqualTo(String value) {
            addCriterion("stu_name <=", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameLike(String value) {
            addCriterion("stu_name like", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameNotLike(String value) {
            addCriterion("stu_name not like", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameIn(List<String> values) {
            addCriterion("stu_name in", values, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameNotIn(List<String> values) {
            addCriterion("stu_name not in", values, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameBetween(String value1, String value2) {
            addCriterion("stu_name between", value1, value2, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameNotBetween(String value1, String value2) {
            addCriterion("stu_name not between", value1, value2, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNumberIsNull() {
            addCriterion("stu_number is null");
            return (Criteria) this;
        }

        public Criteria andStuNumberIsNotNull() {
            addCriterion("stu_number is not null");
            return (Criteria) this;
        }

        public Criteria andStuNumberEqualTo(Integer value) {
            addCriterion("stu_number =", value, "stuNumber");
            return (Criteria) this;
        }

        public Criteria andStuNumberNotEqualTo(Integer value) {
            addCriterion("stu_number <>", value, "stuNumber");
            return (Criteria) this;
        }

        public Criteria andStuNumberGreaterThan(Integer value) {
            addCriterion("stu_number >", value, "stuNumber");
            return (Criteria) this;
        }

        public Criteria andStuNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("stu_number >=", value, "stuNumber");
            return (Criteria) this;
        }

        public Criteria andStuNumberLessThan(Integer value) {
            addCriterion("stu_number <", value, "stuNumber");
            return (Criteria) this;
        }

        public Criteria andStuNumberLessThanOrEqualTo(Integer value) {
            addCriterion("stu_number <=", value, "stuNumber");
            return (Criteria) this;
        }

        public Criteria andStuNumberIn(List<Integer> values) {
            addCriterion("stu_number in", values, "stuNumber");
            return (Criteria) this;
        }

        public Criteria andStuNumberNotIn(List<Integer> values) {
            addCriterion("stu_number not in", values, "stuNumber");
            return (Criteria) this;
        }

        public Criteria andStuNumberBetween(Integer value1, Integer value2) {
            addCriterion("stu_number between", value1, value2, "stuNumber");
            return (Criteria) this;
        }

        public Criteria andStuNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("stu_number not between", value1, value2, "stuNumber");
            return (Criteria) this;
        }

        public Criteria andStuAgeIsNull() {
            addCriterion("stu_age is null");
            return (Criteria) this;
        }

        public Criteria andStuAgeIsNotNull() {
            addCriterion("stu_age is not null");
            return (Criteria) this;
        }

        public Criteria andStuAgeEqualTo(Integer value) {
            addCriterion("stu_age =", value, "stuAge");
            return (Criteria) this;
        }

        public Criteria andStuAgeNotEqualTo(Integer value) {
            addCriterion("stu_age <>", value, "stuAge");
            return (Criteria) this;
        }

        public Criteria andStuAgeGreaterThan(Integer value) {
            addCriterion("stu_age >", value, "stuAge");
            return (Criteria) this;
        }

        public Criteria andStuAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("stu_age >=", value, "stuAge");
            return (Criteria) this;
        }

        public Criteria andStuAgeLessThan(Integer value) {
            addCriterion("stu_age <", value, "stuAge");
            return (Criteria) this;
        }

        public Criteria andStuAgeLessThanOrEqualTo(Integer value) {
            addCriterion("stu_age <=", value, "stuAge");
            return (Criteria) this;
        }

        public Criteria andStuAgeIn(List<Integer> values) {
            addCriterion("stu_age in", values, "stuAge");
            return (Criteria) this;
        }

        public Criteria andStuAgeNotIn(List<Integer> values) {
            addCriterion("stu_age not in", values, "stuAge");
            return (Criteria) this;
        }

        public Criteria andStuAgeBetween(Integer value1, Integer value2) {
            addCriterion("stu_age between", value1, value2, "stuAge");
            return (Criteria) this;
        }

        public Criteria andStuAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("stu_age not between", value1, value2, "stuAge");
            return (Criteria) this;
        }

        public Criteria andStuSexIsNull() {
            addCriterion("stu_sex is null");
            return (Criteria) this;
        }

        public Criteria andStuSexIsNotNull() {
            addCriterion("stu_sex is not null");
            return (Criteria) this;
        }

        public Criteria andStuSexEqualTo(String value) {
            addCriterion("stu_sex =", value, "stuSex");
            return (Criteria) this;
        }

        public Criteria andStuSexNotEqualTo(String value) {
            addCriterion("stu_sex <>", value, "stuSex");
            return (Criteria) this;
        }

        public Criteria andStuSexGreaterThan(String value) {
            addCriterion("stu_sex >", value, "stuSex");
            return (Criteria) this;
        }

        public Criteria andStuSexGreaterThanOrEqualTo(String value) {
            addCriterion("stu_sex >=", value, "stuSex");
            return (Criteria) this;
        }

        public Criteria andStuSexLessThan(String value) {
            addCriterion("stu_sex <", value, "stuSex");
            return (Criteria) this;
        }

        public Criteria andStuSexLessThanOrEqualTo(String value) {
            addCriterion("stu_sex <=", value, "stuSex");
            return (Criteria) this;
        }

        public Criteria andStuSexLike(String value) {
            addCriterion("stu_sex like", value, "stuSex");
            return (Criteria) this;
        }

        public Criteria andStuSexNotLike(String value) {
            addCriterion("stu_sex not like", value, "stuSex");
            return (Criteria) this;
        }

        public Criteria andStuSexIn(List<String> values) {
            addCriterion("stu_sex in", values, "stuSex");
            return (Criteria) this;
        }

        public Criteria andStuSexNotIn(List<String> values) {
            addCriterion("stu_sex not in", values, "stuSex");
            return (Criteria) this;
        }

        public Criteria andStuSexBetween(String value1, String value2) {
            addCriterion("stu_sex between", value1, value2, "stuSex");
            return (Criteria) this;
        }

        public Criteria andStuSexNotBetween(String value1, String value2) {
            addCriterion("stu_sex not between", value1, value2, "stuSex");
            return (Criteria) this;
        }

        public Criteria andStuTypeIsNull() {
            addCriterion("stu_type is null");
            return (Criteria) this;
        }

        public Criteria andStuTypeIsNotNull() {
            addCriterion("stu_type is not null");
            return (Criteria) this;
        }

        public Criteria andStuTypeEqualTo(Byte value) {
            addCriterion("stu_type =", value, "stuType");
            return (Criteria) this;
        }

        public Criteria andStuTypeNotEqualTo(Byte value) {
            addCriterion("stu_type <>", value, "stuType");
            return (Criteria) this;
        }

        public Criteria andStuTypeGreaterThan(Byte value) {
            addCriterion("stu_type >", value, "stuType");
            return (Criteria) this;
        }

        public Criteria andStuTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("stu_type >=", value, "stuType");
            return (Criteria) this;
        }

        public Criteria andStuTypeLessThan(Byte value) {
            addCriterion("stu_type <", value, "stuType");
            return (Criteria) this;
        }

        public Criteria andStuTypeLessThanOrEqualTo(Byte value) {
            addCriterion("stu_type <=", value, "stuType");
            return (Criteria) this;
        }

        public Criteria andStuTypeIn(List<Byte> values) {
            addCriterion("stu_type in", values, "stuType");
            return (Criteria) this;
        }

        public Criteria andStuTypeNotIn(List<Byte> values) {
            addCriterion("stu_type not in", values, "stuType");
            return (Criteria) this;
        }

        public Criteria andStuTypeBetween(Byte value1, Byte value2) {
            addCriterion("stu_type between", value1, value2, "stuType");
            return (Criteria) this;
        }

        public Criteria andStuTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("stu_type not between", value1, value2, "stuType");
            return (Criteria) this;
        }

        public Criteria andStuTelIsNull() {
            addCriterion("stu_tel is null");
            return (Criteria) this;
        }

        public Criteria andStuTelIsNotNull() {
            addCriterion("stu_tel is not null");
            return (Criteria) this;
        }

        public Criteria andStuTelEqualTo(Integer value) {
            addCriterion("stu_tel =", value, "stuTel");
            return (Criteria) this;
        }

        public Criteria andStuTelNotEqualTo(Integer value) {
            addCriterion("stu_tel <>", value, "stuTel");
            return (Criteria) this;
        }

        public Criteria andStuTelGreaterThan(Integer value) {
            addCriterion("stu_tel >", value, "stuTel");
            return (Criteria) this;
        }

        public Criteria andStuTelGreaterThanOrEqualTo(Integer value) {
            addCriterion("stu_tel >=", value, "stuTel");
            return (Criteria) this;
        }

        public Criteria andStuTelLessThan(Integer value) {
            addCriterion("stu_tel <", value, "stuTel");
            return (Criteria) this;
        }

        public Criteria andStuTelLessThanOrEqualTo(Integer value) {
            addCriterion("stu_tel <=", value, "stuTel");
            return (Criteria) this;
        }

        public Criteria andStuTelIn(List<Integer> values) {
            addCriterion("stu_tel in", values, "stuTel");
            return (Criteria) this;
        }

        public Criteria andStuTelNotIn(List<Integer> values) {
            addCriterion("stu_tel not in", values, "stuTel");
            return (Criteria) this;
        }

        public Criteria andStuTelBetween(Integer value1, Integer value2) {
            addCriterion("stu_tel between", value1, value2, "stuTel");
            return (Criteria) this;
        }

        public Criteria andStuTelNotBetween(Integer value1, Integer value2) {
            addCriterion("stu_tel not between", value1, value2, "stuTel");
            return (Criteria) this;
        }

        public Criteria andStuBookIsNull() {
            addCriterion("stu_book is null");
            return (Criteria) this;
        }

        public Criteria andStuBookIsNotNull() {
            addCriterion("stu_book is not null");
            return (Criteria) this;
        }

        public Criteria andStuBookEqualTo(Byte value) {
            addCriterion("stu_book =", value, "stuBook");
            return (Criteria) this;
        }

        public Criteria andStuBookNotEqualTo(Byte value) {
            addCriterion("stu_book <>", value, "stuBook");
            return (Criteria) this;
        }

        public Criteria andStuBookGreaterThan(Byte value) {
            addCriterion("stu_book >", value, "stuBook");
            return (Criteria) this;
        }

        public Criteria andStuBookGreaterThanOrEqualTo(Byte value) {
            addCriterion("stu_book >=", value, "stuBook");
            return (Criteria) this;
        }

        public Criteria andStuBookLessThan(Byte value) {
            addCriterion("stu_book <", value, "stuBook");
            return (Criteria) this;
        }

        public Criteria andStuBookLessThanOrEqualTo(Byte value) {
            addCriterion("stu_book <=", value, "stuBook");
            return (Criteria) this;
        }

        public Criteria andStuBookIn(List<Byte> values) {
            addCriterion("stu_book in", values, "stuBook");
            return (Criteria) this;
        }

        public Criteria andStuBookNotIn(List<Byte> values) {
            addCriterion("stu_book not in", values, "stuBook");
            return (Criteria) this;
        }

        public Criteria andStuBookBetween(Byte value1, Byte value2) {
            addCriterion("stu_book between", value1, value2, "stuBook");
            return (Criteria) this;
        }

        public Criteria andStuBookNotBetween(Byte value1, Byte value2) {
            addCriterion("stu_book not between", value1, value2, "stuBook");
            return (Criteria) this;
        }

        public Criteria andStuFineIsNull() {
            addCriterion("stu_fine is null");
            return (Criteria) this;
        }

        public Criteria andStuFineIsNotNull() {
            addCriterion("stu_fine is not null");
            return (Criteria) this;
        }

        public Criteria andStuFineEqualTo(String value) {
            addCriterion("stu_fine =", value, "stuFine");
            return (Criteria) this;
        }

        public Criteria andStuFineNotEqualTo(String value) {
            addCriterion("stu_fine <>", value, "stuFine");
            return (Criteria) this;
        }

        public Criteria andStuFineGreaterThan(String value) {
            addCriterion("stu_fine >", value, "stuFine");
            return (Criteria) this;
        }

        public Criteria andStuFineGreaterThanOrEqualTo(String value) {
            addCriterion("stu_fine >=", value, "stuFine");
            return (Criteria) this;
        }

        public Criteria andStuFineLessThan(String value) {
            addCriterion("stu_fine <", value, "stuFine");
            return (Criteria) this;
        }

        public Criteria andStuFineLessThanOrEqualTo(String value) {
            addCriterion("stu_fine <=", value, "stuFine");
            return (Criteria) this;
        }

        public Criteria andStuFineLike(String value) {
            addCriterion("stu_fine like", value, "stuFine");
            return (Criteria) this;
        }

        public Criteria andStuFineNotLike(String value) {
            addCriterion("stu_fine not like", value, "stuFine");
            return (Criteria) this;
        }

        public Criteria andStuFineIn(List<String> values) {
            addCriterion("stu_fine in", values, "stuFine");
            return (Criteria) this;
        }

        public Criteria andStuFineNotIn(List<String> values) {
            addCriterion("stu_fine not in", values, "stuFine");
            return (Criteria) this;
        }

        public Criteria andStuFineBetween(String value1, String value2) {
            addCriterion("stu_fine between", value1, value2, "stuFine");
            return (Criteria) this;
        }

        public Criteria andStuFineNotBetween(String value1, String value2) {
            addCriterion("stu_fine not between", value1, value2, "stuFine");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table person
     *
     * @mbggenerated do_not_delete_during_merge Sun Mar 11 17:54:38 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table person
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}