package cn.xf.learn.mapper;

import cn.xf.learn.domin.PersonDO;
import cn.xf.learn.domin.condition.PersonCondition;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    int countByExample(PersonCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    int deleteByExample(PersonCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    int insert(PersonDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    int insertSelective(PersonDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    List<PersonDO> selectByExample(PersonCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    PersonDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    int updateByExampleSelective(@Param("record") PersonDO record, @Param("example") PersonCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    int updateByExample(@Param("record") PersonDO record, @Param("example") PersonCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    int updateByPrimaryKeySelective(PersonDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    int updateByPrimaryKey(PersonDO record);
}