package cn.xf.learn.mapper;

import cn.xf.learn.domin.RecorderDO;
import cn.xf.learn.domin.condition.RecorderCondition;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RecorderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recorder
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    int countByExample(RecorderCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recorder
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    int deleteByExample(RecorderCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recorder
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recorder
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    int insert(RecorderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recorder
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    int insertSelective(RecorderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recorder
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    List<RecorderDO> selectByExample(RecorderCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recorder
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    RecorderDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recorder
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    int updateByExampleSelective(@Param("record") RecorderDO record, @Param("example") RecorderCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recorder
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    int updateByExample(@Param("record") RecorderDO record, @Param("example") RecorderCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recorder
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    int updateByPrimaryKeySelective(RecorderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recorder
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    int updateByPrimaryKey(RecorderDO record);
}