package cn.xf.learn.mapper;

import cn.xf.learn.domin.StroageDO;
import cn.xf.learn.domin.condition.StroageCondition;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StroageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stroage
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    int countByExample(StroageCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stroage
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    int deleteByExample(StroageCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stroage
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stroage
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    int insert(StroageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stroage
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    int insertSelective(StroageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stroage
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    List<StroageDO> selectByExample(StroageCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stroage
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    StroageDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stroage
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    int updateByExampleSelective(@Param("record") StroageDO record, @Param("example") StroageCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stroage
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    int updateByExample(@Param("record") StroageDO record, @Param("example") StroageCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stroage
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    int updateByPrimaryKeySelective(StroageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stroage
     *
     * @mbggenerated Sun Mar 11 17:54:38 CST 2018
     */
    int updateByPrimaryKey(StroageDO record);
}